### ISSUE TITLE
NIS domain should NOT require '.'

### ISSUE THREAD

**Issue by kenmiller316** [bodgit/puppet-yp#8]
Hi,
I have a valid NIS domain name (under RHEL6) that does NOT have a period and I found yp::bind fails to evaluate it because Bodgitlib::Domain type is used which appears to be expecting an LDAP styled domain.  
To test I added a '.lab' to my domain and it worked.

I don't believe this behavior is correct.

Regards,

== k+ ==

**Comment by bodgit** [comment]
What are you using as your domain?

It's currently expecting a DNS-style domain, e.g. `example.com` so if there's only one label, it's expecting that to be a TLD, i.e. just letters. I'm guessing you have non-letters in there?

Probably an oversight on my part.

**Comment by kenmiller316** [comment]
Hi,

It is the period '.' that is required, and shouldn't be, IMHO for NIS/YP domains.  foodomain is a valid nis domain, yet using this module I'm required to change it to foodomain.lab which is fine for lab but not existing deployed domains.  Hence the issue report.
However, everything else looks GREAT so far.
Regards,
== k+ ==

**Comment by mac-reid** [comment]
I am having a similar issue. My nis domain name is along the lines of `foo-bar`, which appears to be valid according to all of the NIS documentation I've seen.

As a workaround, I added `-` to the final block of the Bodgitlib::Domain type definition (`[a-z-]{2,63}` instead of `[a-z]{2,63}`).

**Comment by bodgit** [comment]
I'll probably just relax this to a normal `String` given I can't find any hard rules on the format/syntax.

**Comment by bodgit** [comment]
This will be up on the forge shortly as version 2.0.2, thanks for the bug report!
